### ISSUE TITLE
Data folder?

### ISSUE THREAD

**Issue by akirapink** [koolkdev/ManiacEditor#9]
Da heck?
EDIT: Do you mean a data folder for a mod?

**Comment by OtherworldBob** [comment]
Once you've extracted the Data.rsdk file to a folder - point it to that folder, which is usually named "Data", but you can actually call it anything you like. As long as all the files are present in the correct structure inside the folder you point it to, you should be okay.

A mod that you download would usually only have the changed files, so pointing it there won't work so well.
